### ISSUE TITLE
PHP 7.1 support?

### ISSUE THREAD

**Issue by ashsmith** [realtimedespatch/magento2-orderflow#1]
Currently the composer.json is limited to PHP versions up to 7.1

As a result I cannot currently install the extension. Equally, is there any news on support for Magento 2.2.x and 2.3.x?

**Comment by daniel-ness** [comment]
@ashsmith 

PHP7.1 support was added here https://github.com/realtimedespatch/orderflow-api/commit/30c6b25c2fbd07544242571422dd0c0c7d4ad456#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780
